<?php

declare(strict_types=1);

namespace App\MoonShine\Resources\Mechanic\Pages;

use MoonShine\Contracts\UI\ActionButtonContract;
use MoonShine\Contracts\UI\LayoutContract;
use MoonShine\Laravel\Pages\Crud\IndexPage;
use MoonShine\Contracts\UI\ComponentContract;
use MoonShine\UI\Components\ActionButton;
use MoonShine\UI\Components\Table\TableBuilder;
use MoonShine\Contracts\UI\FieldContract;
use MoonShine\Laravel\QueryTags\QueryTag;
use MoonShine\UI\Components\Metrics\Wrapped\Metric;
use MoonShine\UI\Fields\Checkbox;
use MoonShine\UI\Fields\ID;
use App\MoonShine\Resources\Mechanic\MechanicResource;
use MoonShine\Support\ListOf;
use MoonShine\UI\Fields\Number;
use Throwable;


/**
 * @extends IndexPage<MechanicResource>
 */
class MechanicIndexPage extends IndexPage
{
    protected bool $isLazy = true;
    /**
     * @return list<FieldContract>
     */
    protected function fields(): iterable
    {
        return [
            ID::make(),
            Checkbox::make('Континент', 'is_continent'),
            Checkbox::make('Фэйри', 'is_fairy'),
            Number::make('Континент', 'continent_order')->sortable(),
            Number::make('Фэйри', 'fairy_order')->sortable(),
        ];
    }

    protected function modifyLayout(LayoutContract $layout): LayoutContract
    {
        return parent::modifyLayout($layout); // TODO: Change the autogenerated stub
    }

    /**
     * @return ListOf<ActionButtonContract>
     */
    protected function buttons(): ListOf
    {
        $buttons = parent::buttons();

        $buttons->add(ActionButton::make('test', '#' )->toggleModal(''));

        return $buttons;
    }

    /**
     * @return list<FieldContract>
     */
    protected function filters(): iterable
    {
        return [];
    }

    /**
     * @return list<QueryTag>
     */
    protected function queryTags(): array
    {
        return [];
    }

    /**
     * @return list<Metric>
     */
    protected function metrics(): array
    {
        return [];
    }

    /**
     * @param  TableBuilder  $component
     *
     * @return TableBuilder
     */
    protected function modifyListComponent(ComponentContract $component): ComponentContract
    {
        return $component;
    }

    /**
     * @return list<ComponentContract>
     * @throws Throwable
     */
    protected function topLayer(): array
    {
        return [
            ...parent::topLayer()
        ];
    }

    /**
     * @return list<ComponentContract>
     * @throws Throwable
     */
    protected function mainLayer(): array
    {
        return [
            ...parent::mainLayer()
        ];
    }

    /**
     * @return list<ComponentContract>
     * @throws Throwable
     */
    protected function bottomLayer(): array
    {
        return [
            ...parent::bottomLayer()
        ];
    }
}
